/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pokemon;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.border.Border;
import java.awt.FontFormatException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class ChooseSlotPage extends javax.swing.JFrame {
    
    int saveGameButtonClicked = 0;
    int loadGameButtonClicked = 0;

    /**
     * Creates new form ChooseSlotPage
     */
    public ChooseSlotPage() throws FontFormatException, IOException {
        initComponents();
        try {

            saveGameButton1.setOpaque(false);
            saveGameButton1.setContentAreaFilled(false);
            saveGameButton1.setBorderPainted(false);

            saveGameButton2.setOpaque(false);
            saveGameButton2.setContentAreaFilled(false);
            saveGameButton2.setBorderPainted(false);

            saveGameButton3.setOpaque(false);
            saveGameButton3.setContentAreaFilled(false);
            saveGameButton3.setBorderPainted(false);

            loadGameButton1.setOpaque(false);
            loadGameButton1.setContentAreaFilled(false);
            loadGameButton1.setBorderPainted(false);

            loadGameButton2.setOpaque(false);
            loadGameButton2.setContentAreaFilled(false);
            loadGameButton2.setBorderPainted(false);

            loadGameButton3.setOpaque(false);
            loadGameButton3.setContentAreaFilled(false);
            loadGameButton3.setBorderPainted(false);

            String name1 = ConnectDatabase.getName(1);
            Name1.setText(name1);

            String name2 = ConnectDatabase.getName(2);
            Name2.setText(name2);

            String name3 = ConnectDatabase.getName(3);
            Name3.setText(name3);

            String save1 = ConnectDatabase.checkGame(1);
            Save1.setText(save1);

            String save2 = ConnectDatabase.checkGame(2);
            Save2.setText(save2);

            String save3 = ConnectDatabase.checkGame(3);
            Save3.setText(save3);

            File fontStyle = new File("C:\\Users\\ljmwa\\OneDrive - Universiti Malaya\\OneDrive\\Documents\\NetBeansProjects\\PokemonYF\\POKEMON\\src\\main\\java\\com\\mycompany\\pokemon\\Pictures\\Pokemon Classic.ttf");
            if (!fontStyle.exists()) {
                System.err.println("Font file not found.");
                return;
            }
            Font font1 = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(24f);
            Font font2 = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(10f);
            jLabel2.setFont(font1);
            jLabel3.setFont(font1);
            jLabel4.setFont(font1);
            Name1.setFont(font2);
            Name2.setFont(font2);
            Name3.setFont(font2);
            Save1.setFont(font2);
            Save2.setFont(font2);
            Save3.setFont(font2);
        } catch (FileNotFoundException e) {
            System.err.println("Font file not found: " + e.getMessage());
        } catch (FontFormatException e) {
            System.err.println("Font format error: " + e.getMessage());
            throw e; // Re-throw the exception if needed
        } catch (IOException e) {
            System.err.println("I/O error: " + e.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name2 = new javax.swing.JLabel();
        Name3 = new javax.swing.JLabel();
        Save1 = new javax.swing.JLabel();
        Save2 = new javax.swing.JLabel();
        Save3 = new javax.swing.JLabel();
        Name1 = new javax.swing.JLabel();
        saveGameButton1 = new javax.swing.JButton();
        saveGameButton2 = new javax.swing.JButton();
        saveGameButton3 = new javax.swing.JButton();
        loadGameButton3 = new javax.swing.JButton();
        loadGameButton2 = new javax.swing.JButton();
        loadGameButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name2.setForeground(new java.awt.Color(255, 255, 255));
        Name2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 100, 60));

        Name3.setForeground(new java.awt.Color(255, 255, 255));
        Name3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 100, 60));

        Save1.setForeground(new java.awt.Color(255, 255, 255));
        Save1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 100, 60));

        Save2.setForeground(new java.awt.Color(255, 255, 255));
        Save2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Save2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 100, 60));

        Save3.setForeground(new java.awt.Color(255, 255, 255));
        Save3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Save3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 100, 60));

        Name1.setForeground(new java.awt.Color(255, 255, 255));
        Name1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 100, 60));

        saveGameButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGameButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(saveGameButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 140, 100));

        saveGameButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGameButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(saveGameButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 140, 100));

        saveGameButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGameButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(saveGameButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 140, 100));

        loadGameButton3.setBorder(null);
        loadGameButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(loadGameButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 140, 100));

        loadGameButton2.setForeground(new java.awt.Color(255, 255, 255));
        loadGameButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(loadGameButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 140, 100));

        loadGameButton1.setForeground(new java.awt.Color(255, 255, 255));
        loadGameButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(loadGameButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, 100));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Choose Game Slot");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Load Game:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Start a new Adventure:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ljmwa\\OneDrive - Universiti Malaya\\OneDrive\\Documents\\NetBeansProjects\\PokemonYF\\POKEMON\\src\\main\\java\\com\\mycompany\\pokemon\\Pictures\\DS Assignment\\ChooseSlotPage\\LoadGame (1).png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadGameButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameButton1ActionPerformed
        try {
            loadGameButtonClicked = 1;
            
            MainMenuPage mainMenuPageFrame = new MainMenuPage(loadGameButtonClicked);
            this.dispose();
            mainMenuPageFrame.setVisible(true);
            mainMenuPageFrame.pack();
            mainMenuPageFrame.setLocationRelativeTo(null);
        } catch (FontFormatException ex) {
            Logger.getLogger(ChooseSlotPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadGameButton1ActionPerformed

    private void loadGameButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameButton3ActionPerformed
        try {
            loadGameButtonClicked = 3;
            
            MainMenuPage mainMenuPageFrame = new MainMenuPage(loadGameButtonClicked);
            this.dispose();
            mainMenuPageFrame.setVisible(true);
            mainMenuPageFrame.pack();
            mainMenuPageFrame.setLocationRelativeTo(null);
        } catch (FontFormatException ex) {
            Logger.getLogger(ChooseSlotPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadGameButton3ActionPerformed

    private void saveGameButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGameButton3ActionPerformed
        this.saveGameButtonClicked = 3;
        
        LoadGamePage loadGamePageFrame = new LoadGamePage();
        loadGamePageFrame.setSaveGameButtonClicked(saveGameButtonClicked);
        
        this.dispose();
        
        loadGamePageFrame.setVisible(true);
        loadGamePageFrame.pack();
        loadGamePageFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_saveGameButton3ActionPerformed

    private void saveGameButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGameButton2ActionPerformed
        this.saveGameButtonClicked = 2;
        // Create the ChooseSlotPage frame
        LoadGamePage loadGamePageFrame = new LoadGamePage();
        loadGamePageFrame.setSaveGameButtonClicked(saveGameButtonClicked);
        // Close the current StartPage frame
        this.dispose();
        // Set properties for the ChooseSlotPage frame
        loadGamePageFrame.setVisible(true);
        loadGamePageFrame.pack();
        loadGamePageFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_saveGameButton2ActionPerformed

    private void saveGameButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGameButton1ActionPerformed
        this.saveGameButtonClicked = 1;
        // Create the ChooseSlotPage frame
        LoadGamePage loadGamePageFrame = new LoadGamePage();
        loadGamePageFrame.setSaveGameButtonClicked(saveGameButtonClicked);
        // Close the current StartPage frame
        this.dispose();
        // Set properties for the ChooseSlotPage frame
        loadGamePageFrame.setVisible(true);
        loadGamePageFrame.pack();
        loadGamePageFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_saveGameButton1ActionPerformed

    private void loadGameButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameButton2ActionPerformed
        try {
            loadGameButtonClicked = 2;
            
            MainMenuPage mainMenuPageFrame = new MainMenuPage(loadGameButtonClicked);
            this.dispose();
            mainMenuPageFrame.setVisible(true);
            mainMenuPageFrame.pack();
            mainMenuPageFrame.setLocationRelativeTo(null);
        } catch (FontFormatException ex) {
            Logger.getLogger(ChooseSlotPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loadGameButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseSlotPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseSlotPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseSlotPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseSlotPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ChooseSlotPage().setVisible(true);
                } catch (FontFormatException | IOException ex) {
                    Logger.getLogger(ChooseSlotPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public int saveGameButtonCheck(){
        return saveGameButtonClicked;
    }
    
    public int loadGameButtonCheck(){
        return loadGameButtonClicked;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name3;
    private javax.swing.JLabel Save1;
    private javax.swing.JLabel Save2;
    private javax.swing.JLabel Save3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loadGameButton1;
    private javax.swing.JButton loadGameButton2;
    private javax.swing.JButton loadGameButton3;
    private javax.swing.JButton saveGameButton1;
    private javax.swing.JButton saveGameButton2;
    private javax.swing.JButton saveGameButton3;
    // End of variables declaration//GEN-END:variables
}
